name: Update Leaderboard

on:
  push:
    branches:
      - main

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Validate JSON
      run: python scripts/validate_json.py

    - name: Run leaderboard script
      run: python scripts/generate_leaderboard.py

    - name: Commit and push if changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git diff --staged --quiet || git commit -m "Update leaderboard in README.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
